export {
  trackEvent,
  trackContactFormSubmit,
  trackContactFormSuccess,
  trackContactFormError,
  trackCTAClick,
  trackNavClick,
  trackServicePageView,
  trackBlogPostView,
  trackFAQExpand,
  trackContactClick,
  EVENTS,
  type EventName,
  type EventProperties,
} from './events'
