'use client'

import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
import type { BaseFieldProps } from './field-types'

/**
 * AutoNumberField - Read-only auto-generated number field
 *
 * Displays the auto-generated ID (e.g., LEAD-0001, CON-0042).
 * Value is generated by the database on insert.
 */
export function AutoNumberField({ value, className }: BaseFieldProps) {
  return (
    <div className={cn('text-sm py-2', className)}>
      {value ? (
        <span className="flex items-center gap-2">
          <code className="bg-muted px-2 py-0.5 rounded text-sm font-mono">
            {String(value)}
          </code>
          <Badge variant="outline" className="text-xs">
            Auto
          </Badge>
        </span>
      ) : (
        <span className="text-muted-foreground italic">Generated on save</span>
      )}
    </div>
  )
}
